### PR TITLE
bugfix: compatibility with pymechanical

### PR DESCRIPTION
**Pull request by SMoraisAnsys**
Use ansys-pythonnet (ansys fork) rc 2 to provide consistant libraries as a bundle.

Closes ansys/pyansys#384

### CODE REVIEW

**Review by MaxJPRey — APPROVED** [review]
LGTM.

**Comment by MaxJPRey** [comment]
Adding @maxcapodi78 for visibility.
@SMoraisAnsys Please modify the conda-forge recipe as soon as this PR is merged, to make sure that the dependencies are well synchronized.

**Comment by maxcapodi78** [comment]
> Adding @maxcapodi78 for visibility. @SMoraisAnsys Please modify the conda-forge recipe as soon as this PR is merged, to make sure that the dependencies are well synchronized.

I've just one question: what happens to customers that has already pythonnet installed?

**Comment by koubaa** [comment]
@maxcapodi78 when using pyaedt, nothing. when using pymechanical, it will print a warning message to uninstall it and install ansys-pythonnet

**Pull request merged**
