### PR TITLE
disabling examples post

### PR DESCRIPTION
**Pull request by maxcapodi78**
Those examples continue to fails on documentation build. Added environment variable to avoid disabling them

### CODE REVIEW

**Review by MaxJPRey — APPROVED** [review]

**Comment by MaxJPRey** [comment]
LGTM.

**Comment by jsalant22** [comment]
@maxcapodi78 Is there an error message of any kind from the failed doc builds? I know the UI aspects needed to be disabled, but it looks like maybe there's an issue with pyaedt finding our backend API too.

**Comment by maxcapodi78** [comment]
@jsalant22 it simply hangs after the simulation has finished. it looks to me that the problem is in the methods defined into the example after the simulation is performed. The API commands looks good to me

**Comment by jsalant22** [comment]
@maxcapodi78 Thanks. If there's a way for us to dig into these issues some more and try building the docs on a branch, I'd be happy to help.

**Comment by maxcapodi78** [comment]
@jsalant22  I would suggest you try first running the examples in your machine in non-graphical (this is how Documentation builder works), then try to build documentation on your machine. this is how I typically debug examples on my laptop

**Pull request merged**
