### PR TITLE
FIX: cutout extension

### PR DESCRIPTION
**Pull request by hui-zhou-a**

### CODE REVIEW

**Review by SMoraisAnsys — COMMENTED** [review]
@hui-zhou-a Can you explain those changes ? Is that related to a specific issue ?

**Comment by hui-zhou-a** [comment]
@SMoraisAnsys https://github.com/ansys/pyaedt/issues/5314

**Review by Samuelopez-ansys — CHANGES_REQUESTED** [review]
@hui-zhou-a 

I would also add the project name, because you could have multiple projects opened.

active_project = app.active_project()
active_design = app.active_design()

 project_name = active_project.GetName()

if active_design.GetDesignType() in ["HFSS 3D Layout Design"]:
        design_name = active_design.GetName().split(";")[1]
  else:  # pragma: no cover
        app.logger.debug("Hfss 3D Layout project is needed.")
        app.release_desktop(False, False)
        raise Exception("Hfss 3D Layout designis needed.")

 h3d = ansys.aedt.core.Hfss3dLayout(project=project_name, design=design_name)

**Comment by hui-zhou-a** [comment]
> @hui-zhou-a
> 
> I would also add the project name, because you could have multiple projects opened.
> 
> active_project = app.active_project() active_design = app.active_design()
> 
> project_name = active_project.GetName()
> 
> if active_design.GetDesignType() in ["HFSS 3D Layout Design"]: design_name = active_design.GetName().split(";")[1] else: # pragma: no cover app.logger.debug("Hfss 3D Layout project is needed.") app.release_desktop(False, False) raise Exception("Hfss 3D Layout designis needed.")
> 
> h3d = ansys.aedt.core.Hfss3dLayout(project=project_name, design=design_name)

Done

**Review by Samuelopez-ansys — APPROVED** [review]

**Review by SMoraisAnsys — APPROVED** [review]
LGTM

**Pull request merged**
