### PR TITLE
FIX: Upgrade example model

### PR DESCRIPTION
**Pull request by jsalant22**
D1099705: make sure example model is saved in parasolid format, not acis

### CODE REVIEW

**Comment by jsalant22** [comment]
@bryankaylor When you review, can you just verify that test_22_couplings() runs successfully with 25.1?

**Comment by bryankaylor** [comment]
Looks good, was able to open the project in 25R1 without any issue, approving.

**Review by bryankaylor — APPROVED** [review]

**Comment by bryankaylor** [comment]
> @bryankaylor When you review, can you just verify that test_22_couplings() runs successfully with 25.1?

@jsalant22 Sorry, just approved before seeing your comment, I was able to open the project in 25R1 but haven't run the test. I'll do that now.

**Comment by bryankaylor** [comment]
> @bryankaylor When you review, can you just verify that test_22_couplings() runs successfully with 25.1?

`test_22_couplings` passed on this branch with 25R1, so this should be good to go!

**Pull request merged**
