### PR TITLE
FIX: Duplicate function by @abhandare21 in #5438

### PR DESCRIPTION
**Pull request by abhandare21**
Updated the duplicate function in the modeler_pcb.py file line 761, to allow a list of items to be passed as argument for hfss3dlayout to duplicate.

### CODE REVIEW

**Comment by gmalinve** [comment]
Hi @abhandare21,

Thanks for your contribution. I have one question, why do you need this change? does it bring any benefit to your workflow? do you have any example where this can be useful?

Thanks again,

Giulia

**Comment by abhandare21** [comment]
Hi @gmalinve, I am building a big array of elements in an x-y grid, which requires me to duplicate multiple items in both directions. It is much faster when I pass a list versus running in a for loop.

**Comment by gmalinve** [comment]
@abhandare21 why do you need a for loop if you can duplicate a geometry along a direction with the _duplicate_ method?
I saw your issue, why don't you just create a geometry (without saving it into a list) and then simply duplicate it along x and y direction? like that:
```
# Create a rectangle
rect = h3dl.modeler.create_rectangle(layer_name, origin=['0mm', '0mm'], sizes=['1mm', '1mm'])

# Duplicate the rectangle 5 times in the x direction
rect_x = h3dl.modeler.duplicate(rect, 4, [pitch, 0])

# Duplicate the rectangle 5 times in the y direction
rect_y = h3dl.modeler.duplicate(rect, 4, [0, pitch])
```
With this code snippet you get something like this:
image

I tested your code and it doesn't duplicate along the y direction, I end up having something like this:
image

**Comment by Samuelopez-ansys** [comment]
In addition, did you try 3D Component array? This technique is much efficient for computation:

https://examples.aedt.docs.pyansys.com/version/dev/examples/high_frequency/antenna/array.html

**Comment by abhandare21** [comment]
@gmalinve, the code I have shared in the issue won't work unless you change line 761 in the modeler_pcb.py file

What I want the duplicate function to do is this
image

And if I have to do that with the current code, I need to iterate over a list of items in the x array to duplicate them in the y direction.

If you do a record script through Tools>Record script to file, then the duplicate line is as such
`oEditor.Duplicate(["NAME:options","count:=",4 ],["NAME:elements","rect__3","rect_0","rect__4","rect__5","rect__6"],[0,0.002])`

In order to get this using the duplicate function, you would need to change the existing line 761 from
`self.oeditor.Duplicate(["NAME:options", "count:=", count], ["NAME:elements", ",".join(assignment)], vector)`
to
`self.oeditor.Duplicate(["NAME:options", "count:=", count], ["NAME:elements"]+assignment, vector)`

This is the output of the two lines respectively.
`["NAME:elements", ",".join(assignment)]`

> ['NAME:elements', 'NewObject_RTAS5M,rect__1,rect__3,rect__4,rect__2']

`["NAME:elements"] + assignment`

> ['NAME:elements', 'NewObject_RTAS5M', 'rect__1', 'rect__3', 'rect__4', 'rect__2']

This change should get the code to align with what HFSS is doing.

**Comment by abhandare21** [comment]
@Samuelopez-ansys would this work with 3Dlayout?

**Comment by Samuelopez-ansys** [comment]
It does not work with HFSS 3DLayout right. But a 3D Component in HFSS using pure layout geometry, will still use "Phi mesher". 

If you need more information about how to improve your workflow, please reach the Ansys support team, from my experience, I see more benefits using 3D Component array in HFSS, but maybe I am wrong because I do not know your application

**Comment by abhandare21** [comment]
@Samuelopez-ansys I have about 100 signal and dielectric layer each with about 150ish object on each layer. Hence the ask to update the duplicate function so 3Dlayout users can effectively use the code.

**Comment by Samuelopez-ansys** [comment]
@abhandare21 Thanks for your contribution. We have cherry picked your Pull request, so I will proceed to close this PR.

The new PR is: #5476

**Comment by abhandare21** [comment]
Thanks !

**Pull request closed without merging**
