### PR TITLE
Maxwell impedance BC can now be assigned to faces as well, improved docstring

### PR DESCRIPTION
**Pull request by IreneWoyna**

### CODE REVIEW

**Review by MaxJPRey — APPROVED** [review]
LGTM.

**Comment by Samuelopez-ansys** [comment]
@IreneWoyna Could you add unit test for both cases (bodies and Faces)? Thanks you!

**Comment by IreneWoyna** [comment]
> @IreneWoyna Could you add unit test for both cases (bodies and Faces)? Thanks you!

will do!

**Review by Samuelopez-ansys — APPROVED** [review]
Great job!

**Pull request merged**
