### PR TITLE
replaced default HFSS Solution type to Terminal for version >= 2024.1

### PR DESCRIPTION
**Pull request by maxcapodi78**

### CODE REVIEW

**Comment by MaxJPRey** [comment]
@maxcapodi78 In the title of the PR, you mention that the default Solution type should be `Terminal`.
But in the code it seems it is `Modal`.

It is just to be sure that it is expected.

**Comment by Samuelopez-ansys** [comment]
@MaxJPRey You can see in desing_types that @maxcapodi78 changed the default HFSS design, the main reason is because from AEDT 2023R2, the default is Terminal.

**Review by Samuelopez-ansys — APPROVED** [review]
LGTM

**Comment by MaxJPRey** [comment]
> @MaxJPRey You can see in desing_types that @maxcapodi78 changed the default HFSS design, the main reason is because from AEDT 2023R2, the default is Terminal.

Got it. Thanks @Samuelopez-ansys !

**Pull request merged**
