### PR TITLE
REFACTOR: Renaming filter into filter_order

### PR DESCRIPTION
**Pull request by ramin4667**
This PR renames order to filter_order to make it more meaningful.

### CODE REVIEW

**Comment by SMoraisAnsys** [comment]
Could you please avoid adding the link to tfs (at most refer the issue number).
If possible, could you provide a better explanation as to why you are proposing this changes ?

**Comment by ramin4667** [comment]
> Could you please avoid adding the link to tfs (at most refer the issue number). If possible, could you provide a better explanation as to why you are proposing this changes ?

The link is removed.

**Comment by SMoraisAnsys** [comment]
Thanks @ramin4667, can you explain why this change is more meaningful ? That is not clear to me

**Comment by ramin4667** [comment]
> Member

@SMoraisAnsys The rest of the attributes start with filter_***, and the user could mistakenly use filter_order instead of order. This change makes attribute names consistent.

**Review by SMoraisAnsys — APPROVED** [review]

**Pull request merged**
