### PR TITLE
BUILD: Update requirement of osmnx to greater than 1.1.0 and lower than 2.1

### PR DESCRIPTION
**Pull request by SMoraisAnsys**
## Description
As title says.

## Checklist
- [ ] I have tested my changes locally.
- [x] I have added necessary documentation or updated existing documentation.
- [x] I have followed the coding style guidelines of this project.
- [x] I have added appropriate tests (unit, integration, system).
- [x] I have reviewed my changes before submitting this pull request.
- [x] I have linked the issue or issues that are solved by the PR if any.
- [x] I have agreed with the Contributor License Agreement ([CLA](https://developer.ansys.com/form/cla-acceptance)).

### CODE REVIEW

**Review by MaxJPRey — APPROVED** [review]
LGTM.

**Comment by SMoraisAnsys** [comment]
@Samuelopez-ansys Would it make sense to extend the testing of features related to osmnx or should I do that in another PR?

**Comment by Samuelopez-ansys** [comment]
@

**Comment by SMoraisAnsys** [comment]
> @SMoraisAnsys Why do we need compatibility with previous versions?
> 
> If the output is the same, why not just use the new API?

We could do that but that means that people using older version of osmnx won't be able to use new versions of pyaedt.
This is not a problem in my eyes but I'd rather clean up the dependencies once we move to version `1.0` than doing it right now.
It's an open discussion though :)

**Review by Samuelopez-ansys — APPROVED** [review]
LGTM

**Pull request merged**
