### PR TITLE
CI: remove potential vale warnings

### PR DESCRIPTION
**Pull request by SMoraisAnsys**
At least since version 2.29.3 of vale, titles are also checked by vale. Thus, multiple warning started appearing due to non deterministic behavior when using multiple (differently-cased) entries for the same terme.

The proposed solution consists in reworking the accept.txt file until no more warnings are generated.

### CODE REVIEW

**Review by Samuelopez-ansys — APPROVED** [review]
Great!

**Review by maxcapodi78 — APPROVED** [review]

**Comment by Samuelopez-ansys** [comment]
@SMoraisAnsys Is this PR still a draft?

**Comment by SMoraisAnsys** [comment]
> @SMoraisAnsys Is this PR still a draft?

Yes, I would like to be sure that everything is working as expected.

**Comment by SMoraisAnsys** [comment]
I think the changes are working. Since I was not able to get any error, I added some strange sentence in the documentation to trigger vale and only this sentence got caught. Sentence added "Babedibabedibou rofl"

Vale report :
```
/home/runner/vale --output=/home/runner/work/_actions/errata-ai/vale-action/reviewdog/lib/rdjsonl.tmpl --config=doc/.vale.ini doc
  {"message": "[Vale.Spelling] Did you really mean 'Babedibabedibou'?", "location": {"path": "doc/source/API/Application.rst", "range": {"start": {"line": 31, "column": 1}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'rofl'?", "location": {"path": "doc/source/API/Application.rst", "range": {"start": {"line": 31, "column": 17}}}, "severity": "ERROR"}
  ```

I'll rewrite the history to only keep the changes of interest.
@Samuelopez-ansys Do I change the way the vale work is triggered (either using pyansys action or directly using errata-ai/vale-action@reviewdog) ?

**Comment by Samuelopez-ansys** [comment]
@SMoraisAnsys Could we merge?

**Pull request merged**
