### PR TITLE
BUILD: Bump numpy version to>=1.20.0,<2.3

### PR DESCRIPTION
**Pull request by SMoraisAnsys**
## Description

Follow up of #5116 and #5116 to bump numpy's version bound.
Previously we had issues associated to .NET and TOML handling but most of them have been taken care of. The last thing standing should be fixed with #5555.

## Checklist
- [ ] I have tested my changes locally.
- [x] I have added necessary documentation or updated existing documentation.
- [x] I have followed the coding style guidelines of this project.
- [ ] I have added appropriate tests (unit, integration, system).
- [x] I have reviewed my changes before submitting this pull request.
- [x] I have linked the issue or issues that are solved by the PR if any.
- [x] I have agreed with the Contributor License Agreement ([CLA](https://developer.ansys.com/form/cla-acceptance)).

### CODE REVIEW

**Review by Samuelopez-ansys — APPROVED** [review]

**Review by MaxJPRey — APPROVED** [review]
LGTM.
Thanks for all the previous tasks of yours that allowed us to eventually bump numpy.

**Comment by Samuelopez-ansys** [comment]
@SMoraisAnsys COuld we merge right?

**Comment by SMoraisAnsys** [comment]
@Samuelopez-ansys Let's wait for #5555 merging before merging. I would prefer to check after the .NET changes since they might interact as it was happening in previews PRs.

**Comment by SMoraisAnsys** [comment]
Updating after merging #5555, let's see how things go !

**Pull request merged**
