### PR TITLE
FEAT: Enable harmonic force

### PR DESCRIPTION
**Pull request by JuliusSaitz**

### CODE REVIEW

**Comment by SMoraisAnsys** [comment]
@JuliusSaitz Thanks a lot for opening this PR. We haven't had the time to work on #4779 so it's really great that you are dealing with it. We are working on refactoring our codebase to deprecate some argument names so this PR will have to follow this and keep use of `assignment` instead of `object`.

Pinging @Samuelopez-ansys and @gmalinve for feedback on the changes

**Comment by SMoraisAnsys** [comment]
I took the liberty to "commit" by merging the main branch. Doing so will allow your PR to run the tests correctly.

**Comment by gmalinve** [comment]
@JuliusSaitz good job! thanks for your contribution!
Now you should add some UT to cover the new functionalities you implemented :)

**Comment by SMoraisAnsys** [comment]
@JuliusSaitz Could you please add some tests to your PR ? We enforce new development to be tested to avoid adding failing code to the main branch and also to avoid adding bugs in the future.

If needed we can help you with the argument renaming afterward.

**Comment by JuliusSaitz** [comment]
Hi Sebastien,

Yes, I understand, and I will. It's just a matter of time. Right now, I need to concentrate on other work. Thanks.

Best regards

Julius
________________________________

**Comment by SMoraisAnsys** [comment]
Hi @JuliusSaitz, do you think you'll have time in the comings days/weeks to add the missing tests ? Thanks again for your contribution !

**Comment by Samuelopez-ansys** [comment]
Hi @JuliusSaitz ,

What is the status of this PR? Please could you finish it? If not we will close the PR without merging.

Thanks!

**Comment by JuliusSaitz** [comment]
Hi Samuel,

I really wanted to do this, but the situation with other activities is not really any better. Please, close this without merging. At one point I may return to this activity. Thanks.

Julius



________________________________

**Comment by gmalinve** [comment]
@JuliusSaitz @SMoraisAnsys I'd suggest not closing it. @anur7 is starting contributing in PyAEDT and he maybe take over if he feels comfortable.

**Pull request closed without merging**
