### PR TITLE
Monitors and datasets import/export improvements

### PR DESCRIPTION
**Pull request by lorenzovecchietti**
Change in the handling of datasets and monitor import/export through json configuration.
Changes suggested by @dcrawforAtAnsys so that the configuration file can be validated by a schema.

Previously, the name of monitors and datasets was used as key. Hence, it was impossible to write a schema with unique keys.

Backward compatibility is maintained. No deprecation warning is displayed as I'm not 100% sure it is appropriate. We are changing the format of the json and not actually deprecating anything.

### CODE REVIEW

**Review by dcrawforAtAnsys — APPROVED** [review]
LGTM. This will require more testing against the schema which will come in a subsequent PR.

**Review by Samuelopez-ansys — APPROVED** [review]

**Comment by Samuelopez-ansys** [comment]
@lorenzovecchietti This PR is linked to any Issue?

**Comment by lorenzovecchietti** [comment]
> @lorenzovecchietti This PR is linked to any Issue?

No, @dcrawforAtAnsys reached out to me directly





> LGTM. This will require more testing against the schema which will come in a subsequent PR.

Do we want/neet to wait for this other PR (if it is coming soon) before merging? @Samuelopez-ansys @dcrawforAtAnsys

**Review by MaxJPRey — APPROVED** [review]
LGTM.

**Pull request merged**
