### PR TITLE
added "DecadeCount" "OctaveCount" "ExponentialCount" in parametric sw…

### PR DESCRIPTION
**Pull request by IreneWoyna**
…eep, removed unit from "step"

### CODE REVIEW

**Comment by IreneWoyna** [comment]
It seems that "LogScale" is actually not used at all and could be removed

        elif variation_type == "LogScale":
            sweep_range = "DEC {} {} {}".format(start_point, end_point, step)

**Review by MaxJPRey — APPROVED** [review]
LGTM.

**Review by Samuelopez-ansys — CHANGES_REQUESTED** [review]
@IreneWoyna Great implementation, but you need to add some unit test to pass the CodeCov: 
image

It is not your fault, it was not covered before, but now you touched this part of the code and the bot detected it :) You just need to add these different sweeps in the unittest.

**Comment by gmalinve** [comment]
@IreneWoyna I'd remove the LogScale and add unit test to cover all new cases.

**Review by Samuelopez-ansys — APPROVED** [review]
LGTM

**Pull request merged**
