### PR TITLE
FIX: Only one component per pins is created.

### PR DESCRIPTION
**Pull request by MaxJPRey**
Just renaming the method from `create_components_on_pins()` to `create_component_on_pins()` because based on the code, only one component can be created.

### CODE REVIEW

**Comment by MaxJPRey** [comment]
@maxcapodi78 I don't think that those changes made in #4451 were part of the release 0.8.7. So no need to handle deprecation.

**Review by SMoraisAnsys — APPROVED** [review]
Nice catch

**Review by Samuelopez-ansys — APPROVED** [review]
Should we create a deprecation warning?

**Comment by MaxJPRey** [comment]
> Should we create a deprecation warning?

@Samuelopez-ansys I don't think so as the method was created 5 days ago and it is not part of the last release.
so no one should have ever used it.

**Pull request merged**
