### PR TITLE
TEST: Improve workflow coverage

### PR DESCRIPTION
**Pull request by Samuelopez-ansys**

### CODE REVIEW

**Review by maxcapodi78 — DISMISSED** [review]
Looks great

**Review by myoung301 — COMMENTED** [review]
Looks good from an EMIT perspective. A couple methods in emit_core/revision.py don't have coverage right now, but we can address that later. CC @jsalant22

**Review by maxcapodi78 — APPROVED** [review]

**Comment by Samuelopez-ansys** [comment]
@myoung301 @jsalant22 What do you think regarding the extensions/workflows?

I think EMIT could take advantage of this. Using Tkinter we can create automated workflows inside PyAEDT.  

If the extension requires complex stuff then I would use the pyaedt-common-toolkit approach.

**Review by SMoraisAnsys — APPROVED** [review]
LGTM, great job !
I'd recommend avoiding using environment variables as it is done right now and only use `argparse` (which is something that is already in the workflows/misc.py file.
Using `argparse` to handle CLI arguments is common and good practice IMO

**Review by SMoraisAnsys — DISMISSED** [review]

**Review by maxcapodi78 — APPROVED** [review]

**Review by maxcapodi78 — APPROVED** [review]

**Pull request merged**
