### PR TITLE
BUILD: Remove imageio from requirements

### LINKED ISSUE #4909: Bug located in AEDT Ribbon Bar
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

In Linux, if AEDT is launched through scheduler (Slurm, LSF...) then the environment variable ANSYSEM_ROOTxxx are not necessary available on the machines. We need to set this automatically when console and other ribbon buttons are executed.

### Steps To Reproduce

.

### Which Operating System are you using?

Linux

### Which Python version are you using?

3.10

### Installed packages

.

### PR DESCRIPTION
**Pull request by maxcapodi78**
added environment variable in linux extension.
Close #4909

### CODE REVIEW

**Review by SMoraisAnsys — DISMISSED** [review]
LGTM, imageio was probably missed when extracting pyedb from pyaedt !

**Comment by SMoraisAnsys** [comment]
Are the linux changes related to an issue or something ? Why are they needed ?

**Comment by maxcapodi78** [comment]
> Are the linux changes related to an issue or something ? Why are they needed ?

@SMoraisAnsys Yes. I' didn't enter the issue. I've tested yesterday on our Cluster and it happens that if I open AEDT from SLURM or LSF and then launch the console the variables are obviously not there. So I force the add of the variable before initializing the pyaedt console

**Comment by SMoraisAnsys** [comment]
Seems like imageio is required by pyvista and some test with animated plots are failing.

image

Can you update the PR title to match linux changes and add a comment on imageio in pyproject.toml so that we remember the reason for this requirement ?

**Review by SMoraisAnsys — APPROVED** [review]

**Pull request merged**
