### PR TITLE
FEAT: DXF import updates

### LINKED ISSUE #5520: Cannot import R12 DXF files
### Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### Description of the bug

Importing an R12 DXF file, as exported by certain third-party tools, results in a failure because the layer-checking logic in https://github.com/ansys/pyaedt/blob/e62d2a4c972431536c4c8ea6b607dc8d3278e7fa/src/ansys/aedt/core/application/analysis_3d.py#L1241 assumes the R13 or later format.

### Steps To Reproduce

1. Call https://github.com/ansys/pyaedt/blob/e62d2a4c972431536c4c8ea6b607dc8d3278e7fa/src/ansys/aedt/core/application/analysis_3d.py#L1265 with a path to an R12 DXF file.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

```
annotated-types==0.7.0
ansys-pythonnet==3.1.0rc4
attrs==24.2.0
boolean.py==4.0
CacheControl==0.14.1
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
clr-loader==0.2.6
cyclonedx-python-lib==7.6.2
defusedxml==0.7.1
ezdxf==1.3.4
filelock==3.16.1
fonttools==4.55.1
fpdf2==2.8.1
html5lib==1.1
idna==3.10
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
license-expression==30.4.0
markdown-it-py==3.0.0
mdurl==0.1.2
msgpack==1.1.0
numpy==2.1.3
packageurl-python==0.16.0
packaging==24.2
pandas==2.2.3
pillow==11.0.0
pip-api==0.0.34
pip-requirements-parser==32.0.1
pip_audit==2.7.3
plumbum==1.9.0
psutil==6.1.0
py-serializable==1.1.2
pyaedt==0.11.7
pycparser==2.22
pydantic==2.9.2
pydantic_core==2.23.4
pyedb==0.34.2
Pygments==2.18.0
pyparsing==3.2.0
python-dateutil==2.9.0.post0
pytomlpp==1.0.13
pytz==2024.2
pywin32==308
PyYAML==6.0.2
referencing==0.35.1
requests==2.32.3
rich==13.9.4
rpds-py==0.22.0
rpyc==6.0.1
Rtree==1.3.0
scikit-rf==1.5.0
scipy==1.14.1
six==1.16.0
sortedcontainers==2.4.0
toml==0.10.2
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
webencodings==0.5.1
```

### LINKED ISSUE #5521: Allow modeler-defaulted tolerance for DXF import
### Description of the feature

DXF import in 3D Modeler supports a default tolerance setting.  In the script call, this is implemented by not providing the SelfStitchTolerance argument to ImportDXF.

### Steps for implementing the feature

_No response_

### Useful links and references

_No response_

### LINKED ISSUE #5522: Allow non-graphical DXF import in 2024 R2 and later
### Description of the feature

In 2024 R2.1 at least, non-graphical import of DXF to the 3D Modeler appears to work.

### Steps for implementing the feature

_No response_

### Useful links and references

_No response_

### PR DESCRIPTION
**Pull request by isaacwaldron**
## Description

1. Use [ezdxf](https://github.com/mozman/ezdxf) instead of the existing custom solution to detect the plot layer names from DXFs for import, to support R12 version DXF files.
2. Relax restriction of DXF import in non-graphical mode as it seems to work in 2024 R2 at least.
3. Enable using the modeler's default tolerance for DXF self-stitching by supplying a negative value for self_stitch_tolerance.

## Issue linked

Fixes #5520 
Closes #5521 
Closes #5522 

## Checklist
- [x] I have tested my changes locally.
- [x] I have added necessary documentation or updated existing documentation.
- [x] I have followed the coding style guidelines of this project.
- [x] I have added appropriate tests (unit, integration, system).
- [ ] I have reviewed my changes before submitting this pull request.
- [x] I have linked the issue or issues that are solved by the PR if any.
- [ ] I have agreed with the Contributor License Agreement ([CLA](https://developer.ansys.com/form/cla-acceptance)).

### CODE REVIEW

**Review by Samuelopez-ansys — COMMENTED** [review]
@SMoraisAnsys Please could you check if the added dependency adds any vulnerabilities? 

I think we try to minimize adding new dependencies, mainly for the main ones

**Comment by SMoraisAnsys** [comment]
@isaacwaldron I can't have a look right now but could you let us know if there are other value to add this dependency except for the read method ? As you know, adding a dependency can add a lot of issues regarding dependencies, maintenance, security, ... So I would rather not add a new dependency if we can avoid it.

**Comment by SMoraisAnsys** [comment]
@isaacwaldron Thanks for the feedback, I'll have a better look on this potential dependency. @Samuelopez-ansys Let us discuss next week on that subject as I don't know much about how deeply we leverage DXF in pyaedt.

**Comment by Samuelopez-ansys** [comment]
@isaacwaldron I have pushed a few modifications, please take a look and let us know if you think this could impact your workflow

**Review by Samuelopez-ansys — APPROVED** [review]
LGTM

**Review by SMoraisAnsys — APPROVED** [review]
Agreeing with Samuel's changes. We don't expect many people needing this dependency so I would prefer not having it as a default dependency of PyAEDT.
We'll discuss on creating groups of dependency that make more sense in a near future.
Could you see the changes and let us know ?

**Comment by isaacwaldron** [comment]
@Samuelopez-ansys @SMoraisAnsys the customer reporting this has previously complained about the install weight of PyAEDT, which resulted in some of the current libraries in all being removed from the base set back when this originally happened.  I welcome additional discussion on dependency groups but for now I think restoring the original custom approach with a modification to support the DXF R12 layer table is best since we do not want this in the base set.

**Comment by SMoraisAnsys** [comment]
> @Samuelopez-ansys @SMoraisAnsys the customer reporting this has previously complained about the install weight of PyAEDT, which resulted in some of the current libraries in all being removed from the base set back when this originally happened. I welcome additional discussion on dependency groups but for now I think restoring the original custom approach with a modification to support the DXF R12 layer table is best since we do not want this in the base set.

Is the problem of installation associated to dependencies or to the PyAEDT repo itself ? I don't think we have that many dependencies in `all` tbh. Note that ezdxf would come with numpy at least.
On the topic of dependencies feel free to provide any feedback on sets / subsets of dependencies that could make sense. I plan to try following https://peps.python.org/pep-0735/

**Comment by isaacwaldron** [comment]
@SMoraisAnsys the customer's concern originally was that libraries like matplotlib, pyvista, etc. were in the base set but if you are not planning to do any plotting this significantly increases the download and install weight.

**Comment by Samuelopez-ansys** [comment]
The user can still do:

pip install pyaedt
pip install ezdxf 

And it will work with a minimum size of venv. 

Right now, we can not add ezdxf  to the basic dependencies of PyAEDT, because we are trying to minimize it (if possible).

**Comment by SMoraisAnsys** [comment]
> @SMoraisAnsys the customer's concern originally was that libraries like matplotlib, pyvista, etc. were in the base set but if you are not planning to do any plotting this significantly increases the download and install weight.

Makes sense. We'll probably move to having a `all` target with everything and a subtarget being `plot` for example.

**Review by SMoraisAnsys — COMMENTED** [review]
I didn't check but I assume that old_dxf.dxf is R12 format. Can you rename the file so that we can know that from the file name ?

**Review by Samuelopez-ansys — APPROVED** [review]
LGTM

**Pull request merged**
