### PR TITLE
FEAT: PointCloud Generator for HFSS

### PR DESCRIPTION
**Pull request by DomenicoLoricchio**
## Description
**Please provide a brief description of the changes made in this pull request.**

## Issue linked
**Please mention the issue number or describe the problem this pull request addresses.**

## Checklist
- [ ] I have tested my changes locally.
- [ ] I have added necessary documentation or updated existing documentation.
- [ ] I have followed the coding style guidelines of this project.
- [ ] I have added appropriate tests (unit, integration, system).
- [ ] I have reviewed my changes before submitting this pull request.
- [ ] I have linked the issue or issues that are solved by the PR if any.
- [ ] I have agreed with the Contributor License Agreement ([CLA](https://developer.ansys.com/form/cla-acceptance)).

### CODE REVIEW

**Comment by Samuelopez-ansys** [comment]
@DomenicoLoricchio Good job!

I am updating the extension UI, on this branch:

https://github.com/ansys/pyaedt/pull/5549

I can apply it to your new extension once it is ready to be reviewed.

**Comment by Samuelopez-ansys** [comment]
Please do not miss to add tests and also the corresponding documentation :)

**Comment by Samuelopez-ansys** [comment]
@DomenicoLoricchio The "pip" key in the toml file is not for installing new dependencies.

You should add it to the pyaedt dependencies, but we are trying to minimize the PyAEDT dependencies.

Did you check if pyvista has a similar visualization mode?

**Comment by DomenicoLoricchio** [comment]
> @DomenicoLoricchio The "pip" key in the toml file is not for installing new dependencies.
> 
> You should add it to the pyaedt dependencies, but we are trying to minimize the PyAEDT dependencies.
> 
> Did you check if pyvista has a similar visualization mode?

@Samuelopez-ansys  open3d is not only used for the visualization but also for the generation of the cloud starting from the obj.

Is it possible to use something like that:

try:
    import open3d as o3d
except ModuleNotFoundError:
    import subprocess
    import sys
    print("open3d is not installed. Installing it now...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "open3d"])
    print("open3d has been successfully installed!")
    import open3d as o3d

subprocess and sys are both modules of the standard python library.
with this code only the users interested in this extension will install open3D

**Pull request closed without merging**
