### PR TITLE
CHORE: Added support to Python 3.12

### PR DESCRIPTION
**Pull request by maxcapodi78**
Note: some tests which uses VTK (through Pyvista) fails. They have been disabled. This is probably due to vtk 9.3.0 which is the only compatible with Python 3.12 but has some issues

### CODE REVIEW

**Comment by SMoraisAnsys** [comment]
@maxcapodi78 Do you mind putting this PR as a draft to let me some time to investigate the issue with `vtk` and `pyvista` ?
I could also tackle #4730 while doing so !

**Comment by maxcapodi78** [comment]
> @maxcapodi78 Do you mind putting this PR as a draft to let me some time to investigate the issue with `vtk` and `pyvista` ? I could also tackle #4730 while doing so !

@SMoraisAnsys Done. Consider that all test actually passes (apart the one I've commented)

**Comment by SMoraisAnsys** [comment]
@maxcapodi78 I investigated the problem and I fear that we won't be able to test with `pyvista>=0.43` (which are the only versions compatible with python 3.12). I'll investigate a bit more and open an issue in `pyvista` repo if required.

**Review by Samuelopez-ansys — DISMISSED** [review]

**Review by SMoraisAnsys — APPROVED** [review]

**Review by SMoraisAnsys — APPROVED** [review]

**Review by Samuelopez-ansys — APPROVED** [review]
LGTM

**Review by SMoraisAnsys — APPROVED** [review]

**Pull request merged**
