### PR TITLE
Fix touchstone deepcopy issue

### LINKED ISSUE #3883: Bug located in touchstone_parser
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Bug in touchstone_parser. It looks like it has something to do with grpc. @Samuelopez-ansys 

> 
>   File "C:\ansysdev\pycharm_projects\pyaedt\pyaedt\generic\grpc_plugin.py", line 124, in __Invoke__
>     raise GrpcApiError("Failed to execute grpc AEDT command: {}".format(funcName))
> pyaedt.generic.general_methods.GrpcApiError: Failed to execute grpc AEDT command: __deepcopy__

### Steps To Reproduce

```
from pyaedt import Hfss3dLayout

aedtapp = Hfss3dLayout(r"Project_VHI.aedt",
                       specified_version="2023.2",
                       non_graphical=False, new_desktop_session=False)

tc_data = aedtapp.get_touchstone_data("Setup1")[0]
tc_data.plot_return_losses()

tc_df_data = tc_data.get_mixed_mode_touchstone_data()
tc_df_data.plot_return_losses()

aedtapp.release_desktop(True, False)
```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

pyaedt

### PR DESCRIPTION
**Pull request by Samuelopez-ansys**
Close #3883

### CODE REVIEW

**Comment by Samuelopez-ansys** [comment]
@ansys-reviewer-bot review

**Review by ring630 — APPROVED** [review]
LGTM

**Review by Alberto-DM — APPROVED** [review]
LGTM

**Comment by Samuelopez-ansys** [comment]
@Alberto-DM You were right, with a shallow copy it works. The method is just reordering some Network data, and it does not modify the solution_data, so I prefer this solution. Let me know if you see anything strange before merging.

**Pull request merged**
